version: '3'
services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - "27017:27017"

  postgres_airflow:
    image: "postgres:latest"
    container_name: "postgres_airflow"
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_airflow:/var/lib/postgresql/data
  
  # initdb:
  #   build: .
  #   entrypoint: airflow initdb
  #   depends_on:
  #     - postgres_airflow

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres_airflow
    volumes:
      - ./airflow_files/dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"
    entrypoint: airflow webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  scheduler:
    build: .
    restart: always
    depends_on:
      - postgres_airflow
    volumes:
      - ./airflow_files/dags:/usr/local/airflow/dags
    entrypoint: airflow scheduler
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-scheduler.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  postgres_db:
    image: "postgres:latest"
    container_name: "postgres_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5533:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    container_name: "redis"